FROM registry.redhat.io/openshift4/ose-tools-rhel8@sha256:486b4d2dd0d10c5ef0212714c94334e04fe8a3d36cf619881986201a50f123c7 AS cli-tools
FROM registry.redhat.io/ubi9/python-311@sha256:9101b9924d06a4944649e9cb008496813479d66271ee1f2a1b6ddfc91228c97c

LABEL description="This image provides a data collection service for segment"
LABEL io.k8s.description="This image provides a data collection service for segment"
LABEL io.k8s.display-name="segment collection"
LABEL io.openshift.tags="segment,segment-collection"
LABEL summary="Provides the segment data collection service"
LABEL com.redhat.component="segment-collection"


USER 0

WORKDIR /opt/app-root/src/

COPY . .
COPY --from=cli-tools /usr/bin/oc /usr/local/bin/oc
COPY --from=cli-tools /usr/bin/jq /usr/local/bin/jq

RUN pip install -U pip && pip install -r /opt/app-root/src/requirements.txt --force-reinstall

USER 1001