FROM registry.access.redhat.com/ubi9/python-311@sha256:ade21cd479a66b7d9b92ce5fd4f6633d12f5455b35b590c5c81995f5d01761fc

LABEL description="This image provides a data collection service for segment"
LABEL io.k8s.description="This image provides a data collection service for segment"
LABEL io.k8s.display-name="segment collection"
LABEL io.openshift.tags="segment,segment-collection"
LABEL summary="Provides the segment data collection service"
LABEL com.redhat.component="segment-collection"
LABEL name="segment-collection"


USER 0

WORKDIR /opt/app-root/src/

COPY . .

ADD licenses/ /licenses/

RUN pip install -U pip && pip install -r /opt/app-root/src/requirements.txt --force-reinstall

USER 1001