FROM registry.redhat.io/ubi9/python-311@sha256:526a3ac129953d2b658ca6df77cde212add4e9bc3cc84824cda4bb6db488be9b

LABEL description="This image provides a data collection service for segment"
LABEL io.k8s.description="This image provides a data collection service for segment"
LABEL io.k8s.display-name="segment collection"
LABEL io.openshift.tags="segment,segment-collection"
LABEL summary="Provides the segment data collection service"
LABEL com.redhat.component="segment-collection"


USER 0

WORKDIR /opt/app-root/src/

COPY . .

ADD licenses/ /licenses/

RUN pip install -U pip && pip install -r /opt/app-root/src/requirements.txt --force-reinstall

USER 1001