FROM registry.access.redhat.com/ubi9/python-312@sha256:3e4ad0f46732b83be01f57c6df47433c83ca04c9d329f6ddd735a2896880642a

LABEL description="This image provides a data collection service for segment"
LABEL io.k8s.description="This image provides a data collection service for segment"
LABEL io.k8s.display-name="segment collection"
LABEL io.openshift.tags="segment,segment-collection"
LABEL summary="Provides the segment data collection service"
LABEL com.redhat.component="segment-collection"
LABEL name="segment-collection"


USER 0

WORKDIR /opt/app-root/src/

COPY . .

ADD licenses/ /licenses/

RUN pip install -U pip && pip install -r /opt/app-root/src/requirements.txt --force-reinstall

USER 1001