[metadata]
name = "SegmentBackupJob"
version = "1.0"

[project]
requires-python = ">=3.11"
name = "SegmentBackupJob"
version = "1.0"
dependencies = [
    'segment-analytics-python==2.3.6',
    'PyYAML==6.0.2',
    'PyJWT>=2.13.0',
    'kubernetes==29.0.0',
    'openshift==0.13.2',
    'setuptools-scm==10.0.5',
    'setuptools>=82.0.1',
    'idna==3.10',
    'calver==2025.4.17',
    'types-psutil==7.2.2.20260518',
    'types-setuptools==82.0.0.20260518'
]
